features({
	'autoupdater',
	'config-mode-mesh-vpn',
	'config-mode-domain-select',
	'ebtables-filter-multicast',
	'ebtables-filter-ra-dhcp',
	'ebtables-limit-arp',
	'mesh-batman-adv-15',
	'respondd',
	'status-page',
	'web-advanced',
	'web-wizard',
})

packages({
	'iwinfo',
	'ffac-autoupdater-wifi-fallback',
	'respondd-module-airtime',
	'ffac-weeklyreboot',
	'ffmuc-mesh-vpn-wireguard-vxlan',
})
